# Generated by Django 3.0.5 on 2020-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('student_roll', models.IntegerField()),
                ('student_section', models.CharField(max_length=10)),
                ('student_class', models.CharField(max_length=5)),
            ],
        ),
    ]
