# Generated by Django 3.0.5 on 2020-04-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_roll',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_section',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
    ]
